.\"     Title: git-cola
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/30/2014
.\"    Manual: Git Manual
.\"    Source: Git
.\"
.TH "GIT\-COLA" "1" "01/30/2014" "Git" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-cola - The highly caffeinated git GUI
.SH "SYNOPSIS"
\fIgit cola\fR [options] [sub\-command]
.SH "DESCRIPTION"
\fIgit\-cola\fR is a sleek and powerful git GUI\.
.SH "OPTIONS"
.PP
\-\-amend
.RS 4
Start \fIgit\-cola\fR in amend mode\.
.RE
.PP
\-g, \-\-git\-path
.RS 4
Specifies the path to the \fIgit\fR binary\.
.RE
.PP
\-\-prompt
.RS 4
Prompt for a git repository instead of using the current directory\.
.RE
.PP
\-r, \-\-repo=<path>
.RS 4
Run \fIgit\-cola\fR on the git repository in <path>\. Defaults to the current directory\.
.RE
.PP
\-\-version
.RS 4
Print the \fIgit\-cola\fR version and exit\.
.RE
.SH "SUB-COMMANDS"
.PP
am
.RS 4
Apply patches\.
.RE
.PP
archive
.RS 4
Export tarballs from Git\.
.RE
.PP
branch
.RS 4
Create branches\.
.RE
.PP
browse
.RS 4
Browse tracked files\.
.RE
.PP
config
.RS 4
Configure \fIgit\-cola\fR settings\.
.RE
.PP
dag
.RS 4
Start the \fIgit\-dag\fR visualizer\.
.RE
.PP
diff
.RS 4
Diff changed files\.
.RE
.PP
fetch
.RS 4
Fetch remote branches\.
.RE
.PP
grep
.RS 4
Use git grep to search for content\.
.RE
.PP
merge
.RS 4
Merge branches\.
.RE
.PP
pull
.RS 4
Fetch and merge remote branches\.
.RE
.PP
push
.RS 4
Push branches to remotes\.
.RE
.PP
rebase
.RS 4
Start an interactive rebase\.
.RE
.PP
remote
.RS 4
Create and edit remotes\.
.RE
.PP
search
.RS 4
Search for commits\.
.RE
.PP
stash
.RS 4
Stash modifications\.
.RE
.PP
tag
.RS 4
Create tags\.
.RE
.PP
version
.RS 4
Print the \fIgit\-cola\fR version\.
.RE
.SH "CONFIG VARIABLES"
.PP
cola\.savewindowsettings
.RS 4
\fIgit\-cola\fR will remember its window settings when set to true\. These settings are saved in $HOME/\.config/git\-cola\.
.RE
.PP
cola\.fileattributes
.RS 4
Enables per\-file linkgit:gitattributes[5] encoding support when set to true\. This tells \fIgit\-cola\fR to honor the configured encoding when displaying and applying diffs\.
.RE
.PP
cola\.fontdiff
.RS 4
Specifies the font to use for \fIgit\-cola\fR\'s diff display\.
.RE
.PP
cola\.browserdockable
.RS 4
Whether to create a dock widget with the \fIBrowser\fR tool\. Defaults to \fIfalse\fR to speedup startup time\.
.RE
.PP
cola\.inotify
.RS 4
Set to \fIfalse\fR to disable inotify support\. Defaults to \fItrue\fR when the \fIpyinotify\fR module is available\.
.RE
.PP
cola\.linebreak
.RS 4
Whether to automatically break long lines while editing commit messages\. Defaults to \fItrue\fR\. This setting is configured using the \fIPreferences\fR dialog, but it can be toggled for one\-off usage using the commit message editor\(cqs settings sub\-menu\.
.RE
.PP
cola\.tabwidth
.RS 4
The number of columns occupied by a tab character\.
.RE
.PP
cola\.textwidth
.RS 4
The number of columns used for line wrapping\. Tabs are counted according to cola\.tabwidth\.
.RE
.PP
cola\.readsize
.RS 4
\fIgit\-cola\fR avoids reading large binary untracked files\. The maximum size to read is controlled by cola\.readsize and defaults to 2048\.
.RE
.PP
gui\.diffcontext
.RS 4
The number of diff context lines used and displayed by \fIgit\-cola\fR\.
.RE
.PP
gui\.displayuntracked
.RS 4
\fIgit\-cola\fR avoids showing untracked files when set to false\.
.RE
.PP
gui\.editor
.RS 4
The default text editor is controlled by gui\.editor\. The config variable overrides the EDITOR environment variable\.
.RE
.PP
gui\.historybrowser
.RS 4
Specifies the history browser to use when visualizing history\.
.RE
.PP
diff\.tool
.RS 4
The default diff tool to use\.
.RE
.PP
merge\.tool
.RS 4
The default merge tool to use\.
.RE
.PP
user\.email
.RS 4
Your email address to be recorded in any newly created commits\. Can be overridden by the \fIGIT_AUTHOR_EMAIL\fR, \fIGIT_COMMITTER_EMAIL\fR, and \fIEMAIL\fR environment variables\. See linkgit:git\-commit\-tree[1]\.
.RE
.PP
user\.name
.RS 4
Your full name to be recorded in any newly created commits\. Can be overridden by the \fIGIT_AUTHOR_NAME\fR and \fIGIT_COMMITTER_NAME\fR environment variables\. See linkgit:git\-commit\-tree[1]\.
.RE
See linkgit:git\-config[1] for more details\.
.SH "ENVIRONMENT VARIABLES"
.PP
EDITOR
.RS 4
Specifies the default editor to use\. This is ignored when the git config variable gui\.editor is defined\.
.RE
.PP
GIT_COLA_TRACE
.RS 4
When defined, \fIgit\-cola\fR logs \fIgit\fR commands to stdout\. When set to \fIfull\fR, \fIgit\-cola\fR also logs the exit status and output\. When set to \fItrace\fR, \fIgit\-cola\fR logs to the \fIConsole\fR widget\.
.RE
.SH "LANGUAGE SETTINGS"
\fIgit\-cola\fR automatically detects your language and presents some translations when available\. This may not be desired, or you may want \fIgit\-cola\fR to use a specific language\.

You can make \fIgit\-cola\fR use an alternative language by creating a ~/\.config/git\-cola/language file containing the standard two\-letter gettext language code, e\.g\. "en", "de", "ja", "zh", etc\.::

.sp
.RS 4
.nf
echo en >~/\.config/git\-cola/language
.fi
.RE
.SH "SOURCE"
A \fIgit\-cola\fR development repository can be obtained via git:

.sp
.RS 4
.nf
git clone git://github\.com/git\-cola/git\-cola\.git
.fi
.RE
.SH "LINKS"
.PP
\fIgit\-cola\fR homepage
.RS 4
\fIhttp://git\-cola\.github\.io/\fR
.RE
.PP
\fIgit\-cola\fR sources on github
.RS 4
\fIhttps://github\.com/git\-cola/git\-cola/\fR
.RE
.SH "SEE ALSO"
.PP
linkgit:git\-difftool[1]
.RS 4
Compare changes using common merge tools\.
.RE
.PP
linkgit:gitk[1]
.RS 4
The git repository browser\. Shows branches, commit history and file differences\. gitk is the utility started by \fIgit\-cola\fR\'s Repository Visualize actions\.
.RE
.SH "GIT"
\fIgit\-cola\fR is independently developed from the linkgit:git[7] suite, but you can use it just like any other git command, e\.g\. git cola\.
.SH "AUTHOR"
Written by David Aguilar <\fIdavvid@gmail\.com\fR\&[1]>\.
.SH "NOTES"
.IP " 1." 4
davvid@gmail.com
.RS 4
\%mailto:davvid@gmail.com
.RE
